# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_raw', models.CharField(max_length=1000)),
                ('sms_body', models.CharField(max_length=2000)),
                ('sms_to', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_from', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'SMS received/sent',
            },
        ),
    ]
